### ISSUE TITLE
Error compiling Marlin 2.1.x for Auto-Z align

### ISSUE THREAD

**Issue by JairoGuGe** [makerbase-mks/MKS-TinyBee#67]
I have a homemade 3D printer that is similar to a Prusa i3 MK3S+. It has a MKS Tinybee mainboard (Marlin 2.0.9.2), it has two motors for the Z axis, with independent steppers drivers, so Auto Z-Align can be done and it works perfectly.

I want to update to version Marlin-bugfix-2.1.x, but after making all the modifications to accommodate it to my printer, when compiling the code I get the following error:

Marlin/src/HAL/ESP32/../../inc/SanityCheck.h:3829:8: error: #error "Z_STEPPER_ALIGN_STEPPER_XY requires 3 or 4 Z steppers."

And I have not been able to solve that error, it should work, because in the previous version it works perfectly with two Z steppers. I don't understand why that common configuration of Z axes and steppers doesn't work in 2.1.x.
